let div1 = document.querySelector("#elzero");
let div2 = document.querySelector(".element");
let div3 = document.querySelector("div");
let div4 = document.querySelector('[name="js"]');
let div5 = document.querySelectorAll("div")[0];
let div6 = document.querySelectorAll("#elzero")[0];
let div7 = document.querySelectorAll(".element")[0];
let div8 = document.querySelectorAll('[name="js"]')[0];
let div9 = document.getElementById("elzero");
let div10 = document.getElementsByTagName("div")[0];
let div11 = document.getElementsByClassName("element")[0];
let div12 = document.getElementsByName("js");
let div13 = document.body.childNodes[1];
let div14 = document.body.children[0];
let div15 = document.body.firstElementChild;

console.log(div1);
console.log(div2);
console.log(div3);
console.log(div4);
console.log(div5);
console.log(div6);
console.log(div7);
console.log(div8);
console.log(div9);
console.log(div10);
console.log(div11);
console.log(div12);
console.log(div13);
console.log(div14);
console.log(div15);
